# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f75c645d04cefe016859e5fae3f446fb16edba1ab468c7e861776b7f8737fb4b65f95266f4556d484ad90ec0783f6544a1142ef0ac6a3e34b3c0f9f382507331

test:
  secret_key_base: c936006c74e75eb8a979cd182c781607af5efd4d00b11ebec3b632b1f8b025a95a952b6a966084be57c1dd187130b20daa873a71bcc089eb64ab768bf400ac10

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
